language: node_js
node_js:
  - "v8.10.0"
services:
  - postgresql
env: 
  - DATABASE_URL='postgresql://postgres@localhost:5432/myusers'
before_script:
  - psql -c 'create database myusers;' -U postgres

